sudo: false
language: node_js
node_js:
  - "7"
  - "6"
addons:
  apt:
    packages:
      - imagemagick
script:
  - npm run lint
  - npm test
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
